name: Create PDF File

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 # this checks out the repo in the ubuntu container
      
      # Downloading the binaries directly, because they are newer and work better, than the ones that come with Ubuntu latest.
      - name: "Install pandoc and wkhtmltopdf"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.0.1/pandoc-3.0.1-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt install ./pandoc-3.0.1-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

      - name: "Build Markdown File"
        run: |
          cd resume_builder
          python3 md_generator.py
          python3 cover-letter_generator.py
          python3 html_generator.py
          cd -

      - name: "Convert MD to HTML"
        run: |
          pandoc resume_builder/resume.md -f markdown -t html -c resume_builder/resume-stylesheet.css -s -o output/${{github.actor}}-resume.html

      - name: "Convert HTML to PDF "
        run: "wkhtmltopdf --enable-local-file-access output/${{github.actor}}-resume.html resume.pdf"
      # run: |
      #     /usr/bin/pandoc -standalone --output=output/resume.pdf --css=resume-stylesheet.css --from=markdown --to=pdf --pdf-engine=/usr/bin/wkhtmltopdf resume.md
      # - uses: actions/upload-artifact@master
      #   with: # basically this will put resume.md, resume.html, resume.pdf and resume-stylesheet.css in a zip file.
      #     name: ${{ github.actor }}'s Resume
      #     path: output

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updating files created by workflow

      # - name: Commit and push artifacts to the repository
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #     git add output/
      #     git commit -m "Add resume artifacts for ${{ github.actor }}"
      #     git push origin HEAD:main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
